# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 30, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnGenerateKey = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerateKey.setGeometry(QtCore.QRect(660, 40, 93, 28))
        self.btnGenerateKey.setObjectName("btnGenerateKey")
        self.lblPlainText = QtWidgets.QLabel(self.centralwidget)
        self.lblPlainText.setGeometry(QtCore.QRect(40, 120, 81, 31))
        self.lblPlainText.setObjectName("lblPlainText")
        self.txtPlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.txtPlainText.setGeometry(QtCore.QRect(130, 100, 371, 87))
        self.txtPlainText.setObjectName("txtPlainText")
        self.lblCipherText = QtWidgets.QLabel(self.centralwidget)
        self.lblCipherText.setGeometry(QtCore.QRect(40, 270, 71, 31))
        self.lblCipherText.setObjectName("lblCipherText")
        self.txtCipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.txtCipherText.setGeometry(QtCore.QRect(130, 260, 371, 87))
        self.txtCipherText.setObjectName("txtCipherText")
        self.lblInformation = QtWidgets.QLabel(self.centralwidget)
        self.lblInformation.setGeometry(QtCore.QRect(550, 120, 71, 31))
        self.lblInformation.setObjectName("lblInformation")
        self.txtInformation = QtWidgets.QTextEdit(self.centralwidget)
        self.txtInformation.setGeometry(QtCore.QRect(670, 90, 361, 87))
        self.txtInformation.setObjectName("txtInformation")
        self.lblSignature = QtWidgets.QLabel(self.centralwidget)
        self.lblSignature.setGeometry(QtCore.QRect(570, 280, 71, 31))
        self.lblSignature.setObjectName("lblSignature")
        self.txtSignature = QtWidgets.QTextEdit(self.centralwidget)
        self.txtSignature.setGeometry(QtCore.QRect(670, 260, 361, 87))
        self.txtSignature.setObjectName("txtSignature")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(130, 370, 93, 28))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setGeometry(QtCore.QRect(400, 370, 93, 28))
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.btnSign = QtWidgets.QPushButton(self.centralwidget)
        self.btnSign.setGeometry(QtCore.QRect(710, 370, 93, 28))
        self.btnSign.setObjectName("btnSign")
        self.btnVerify = QtWidgets.QPushButton(self.centralwidget)
        self.btnVerify.setGeometry(QtCore.QRect(890, 370, 93, 28))
        self.btnVerify.setObjectName("btnVerify")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA Cipher"))
        self.label.setText(_translate("MainWindow", "RSA Cipher"))
        self.btnGenerateKey.setText(_translate("MainWindow", "Generate Keys"))
        self.lblPlainText.setText(_translate("MainWindow", "Plain Text:"))
        self.lblCipherText.setText(_translate("MainWindow", "CipherText:"))
        self.lblInformation.setText(_translate("MainWindow", "Information:"))
        self.lblSignature.setText(_translate("MainWindow", "Signature:"))
        self.btnEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btnDecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btnSign.setText(_translate("MainWindow", "Sign"))
        self.btnVerify.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
